# Generated by Django 4.1.5 on 2023-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_code", models.CharField(max_length=255, unique=True)),
                ("user_code", models.CharField(max_length=255, unique=True)),
                ("verification_uri", models.TextField(default="", null=True)),
                ("verification_uri_complete", models.TextField(default="", null=True)),
                ("expires_in", models.IntegerField(default=0)),
                ("interval", models.IntegerField(default=0)),
            ],
        ),
    ]
