# Generated by Django 4.1.5 on 2023-01-14 16:40

from django.db import migrations, models
import my_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ("my_auth", "0003_devicecredential_client_id_devicecredential_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecredential",
            name="auth_time",
            field=models.IntegerField(default=my_auth.models.now_timestamp),
        ),
    ]
